-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
--
-- Add any additional autocmds here
-- with `vim.api.nvim_create_autocmd`
--
-- Or remove existing autocmds by their group name (which is prefixed with `lazyvim_` for the defaults)
-- e.g. vim.api.nvim_del_augroup_by_name("lazyvim_wrap_spell")

-- Autoformat PHP files with Laravel Pint on save
--vim.api.nvim_create_autocmd("BufWritePre", {
--#  pattern = "*.php",
--#  callback = function()
--#    -- run Pint only on the current file
--#    local file = vim.fn.expand("%:p")
--#    vim.cmd("silent! !./vendor/bin/pint " .. file)
--#  end,
--#})
